name: jaifulfood_k6
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  curved_navigation_bar: ^1.0.6
  cached_network_image: ^3.4.1
  provider: ^6.1.2
  url_launcher: ^6.0.20
  google_maps_flutter: ^2.0.6

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    # รูปภาพ
    - assets/banners/Korean_Food.png
    - assets/banners/1.png
    - assets/banners/2.png
    - assets/banners/3.png
    - assets/banners/4.png
    
    - assets/cojohn.png
  fonts:
    - family: LINESeedSansTH_A_Bd
      fonts:
        - asset: assets/fonts/LINESeedSansTH_A_Bd.ttf
    - family: LINESeedSansTH_A_Rg
      fonts:
        - asset: assets/fonts/LINESeedSansTH_A_Rg.ttf
       
        

